name: CI
on: [push, pull_request]
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.CI_AWS_CLIENT_ID }}
  AWS_DEFAULT_REGION: "eu-west-1"
  AWS_SECRET_ACCESS_KEY: ${{ secrets.CI_AWS_CLIENT_SECRET }}
  NDLA_AWS_ECR_REPO: ${{ secrets.NDLA_AWS_ECR_REPO }}
  CI_RELEASE_ROLE: ${{ secrets.CI_RELEASE_ROLE }}
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  NDLA_RELEASES: ${{ secrets.NDLA_RELEASES }}
  GH_TOKEN: ${{ secrets.CI_NOW_GH_TOKEN }}
  NOW_TOKEN: ${{ secrets.NOW_TOKEN }}
  GH_PR_NUMBER: ${{ github.event.number }}
  GH_PR_REPO: ${{ github.event.pull_request.head.repo.full_name }}
  GH_PR_SHA: ${{ github.event.pull_request.head.sha }}
  CYPRESS_NDLA_END_TO_END_TESTING_CLIENT_ID: ${{ secrets.OPEN_PUBLIC_TEST_CLIENT_ID }}
  CYPRESS_NDLA_END_TO_END_TESTING_CLIENT_SECRET: ${{ secrets.OPEN_PUBLIC_TEST_CLIENT_SECRET }}
  CYPRESS_NDLA_END_TO_END_TESTING_AUDIENCE: "ndla_system"
  CYPRESS_NDLA_END_TO_END_TESTING_GRANT_TYPE: "client_credentials"
  CYPRESS_RECORD_KEY: ${{ secrets.LEARNINGPATH_FRONTEND_CYPRESS_RECORD_KEY }}
  NDLA_LEARNING_PATH_CLIENT_ID: ${{ secrets.NDLA_LEARNINGPATH_CLIENT_ID }}
  NDLA_LEARNING_PATH_CLIENT_SECRET: ${{ secrets.NDLA_LEARNINGPATH_CLIENT_SECRET }}
jobs:
  unit_tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: "Login to ECR repo"
        run: RES=$(aws sts assume-role --role-arn $CI_RELEASE_ROLE --role-session-name github-actions-ecr-login)
          AWS_ACCESS_KEY_ID=$(echo $RES | jq -r .Credentials.AccessKeyId)
          AWS_SECRET_ACCESS_KEY=$(echo $RES | jq -r .Credentials.SecretAccessKey)
          AWS_SESSION_TOKEN=$(echo $RES | jq -r .Credentials.SessionToken)
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin $NDLA_AWS_ECR_REPO
      - name: "Login to dockerhub"
        run: echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            .eslintcache
            ~/.npm
            ~/.cache/Cypress
          key: ${{ runner.os }}-deps-${{ hashFiles('**/yarn.lock') }}
      - name: "Install"
        run: yarn install --frozen-lockfile
      - name: "Check-all"
        run: yarn check-all
      - name: "Build"
        run: yarn build
      - name: "e2e-ci"
        uses: cypress-io/github-action@v2
        run: yarn e2e-ci
      - name: "Deploy now build"
        run: yarn ndla-scripts now-github
        continue-on-error: true
